### ISSUE TITLE
Delayed chapters failing

### ISSUE THREAD

**Issue by NLZ** [Rudoal/mdownloader#5]
Delayed chapters are failing because they have no server field in them ([see example](https://mangadex.org/api/v2/chapter/1109506?saver=0))

Here is the failing code, putting the status check before the server extraction seems to work.
I would also add a print that skipping x chapter because y status.

https://github.com/Rudoal/mdownloader/blob/9114ed091215d9da60ee2f2526c78d6c9a214065/components/downloader.py#L100-L104

**Comment by Rudoal** [comment]
I was meant to add an option for delayed chapters from before but didn't do so, but I've added it in the upcoming update, 2.7.2.

**Comment by NLZ** [comment]
Oh, it still fails with externals, so I would move the server url extraction to somewhere before you call it:

https://github.com/Rudoal/mdownloader/blob/9114ed091215d9da60ee2f2526c78d6c9a214065/components/downloader.py#L142-L144
